# Generated by Django 4.0.3 on 2022-05-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field11', models.IntegerField()),
                ('field12', models.IntegerField()),
                ('field13', models.IntegerField()),
                ('field14', models.IntegerField()),
                ('field21', models.IntegerField()),
                ('field22', models.IntegerField()),
                ('field23', models.IntegerField()),
                ('field24', models.IntegerField()),
                ('field31', models.IntegerField()),
                ('field32', models.IntegerField()),
                ('field33', models.IntegerField()),
                ('field34', models.IntegerField()),
                ('field41', models.IntegerField()),
                ('field42', models.IntegerField()),
                ('field43', models.IntegerField()),
                ('field44', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone1', models.IntegerField()),
                ('stone2', models.IntegerField()),
                ('stone3', models.IntegerField()),
                ('stone4', models.IntegerField()),
                ('stone5', models.IntegerField()),
                ('stone6', models.IntegerField()),
                ('stone7', models.IntegerField()),
                ('stone8', models.IntegerField()),
                ('stone9', models.IntegerField()),
                ('stone10', models.IntegerField()),
                ('stone11', models.IntegerField()),
                ('stone12', models.IntegerField()),
                ('stone13', models.IntegerField()),
                ('stone14', models.IntegerField()),
                ('stone15', models.IntegerField()),
                ('stone16', models.IntegerField()),
            ],
        ),
    ]
